### ISSUE TITLE
Application Error when linking 0.10.1 agent

### ISSUE THREAD

**Issue by MadeByIToncek** [playit-cloud/playit-agent#52]
So I downloaded the new agent, went to log in and assigned it the default name. The site then thrown this error and playit client just closed.

Application Error
Error: Unexpected Server Error
    at handleDataRequestRR (/usr/server/app/node_modules/@remix-run/server-runtime/dist/server.js:128:31)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at requestHandler (/usr/server/app/node_modules/@remix-run/server-runtime/dist/server.js:55:18)
    at /usr/server/app/node_modules/@remix-run/express/dist/server.js:39:22

**Comment by MadeByIToncek** [comment]
Yes...even with the old client

**Comment by MadeByIToncek** [comment]
Okay so the page cache is making fun of me, if I refresh it, it shows only my old agent, when I refresh it again, it shows four agents 💀

**Comment by MadeByIToncek** [comment]
New error, this time in the client

Program approved :). Secret code being setup.Error: ApiError(Auth(InvalidAgentKey))

**Comment by MadeByIToncek** [comment]
Working now!
